/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package authenticate.gateway;

import static authenticate.gateway.app.util.CommonUtils.getSystemEnvProperty;
import static authenticate.gateway.app.util.ConstantUtils.SERVER_PORT;
import static java.util.Collections.singletonMap;

import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.scheduling.annotation.EnableScheduling;
import reactor.core.publisher.Hooks;

@Slf4j
@EnableScheduling
@SpringBootApplication
public class App {

  public static void main(String[] args) {
    log.info("Begin authenticate-gateway initialization...");
    // required for traceId/spanId logging
    Hooks.enableAutomaticContextPropagation();

    SpringApplication app = new SpringApplication(App.class);
    app.setDefaultProperties(
        singletonMap("server.port", getSystemEnvProperty(SERVER_PORT, "8080")));
    app.run(args);
    log.info("End authenticate-gateway initialization...");
  }
}
