spring:
  application:
    name: authenticate-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      httpclient:
        connect-timeout: 5000
        response-timeout: 15000

management:
  endpoints:
    web:
      exposure:
        include:
          - health
      base-path: /authenticate-gateway/actuator
