spring:
  application:
    name: authenticate-gateway
  task:
    scheduling:
      pool:
        size: 10
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      httpclient:
        connect-timeout: 5000
        response-timeout: 15000

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: shutdown
      base-path: /authenticate-gateway/actuator
  tracing:
    enabled: true
    propagation:
      type: w3c
    baggage:
      enabled: true
